app:
  name: "web_app"
  mode: "release"
  port: ":8090"
  startTime: "2021-12-03"
  machineID: 1

log:
  level: "debug"
  fileName: "web_app.log"
  maxSize: 200
  maxAge: 30
  maxBackup: 7

mysql:
  host: "127.0.0.1:3306"
  user: "root"
  password: "123456"
  dbname: "db_gin"
  MaxOpenConns: 20
  MaxIdleConns: 10
redis:
  host: "127.0.0.1:6379"
  password: ""
  db: 0
  poolSize: 20